#!/bin/bash

set -euo pipefail

db_prefix=lo_test_

dbgrouplist=
for i in `seq 0 4`
do
	db=$db_prefix$i
	./bucardo add db $db dbname=$db user=bucardo
	dbgrouplist="$dbgrouplist $db:source"
done

./bucardo add dbgroup lo_test $dbgrouplist

./bucardo add sync lo_test_delta dbgroup=lo_test tables=lo_store,lo_store_multi
./bucardo add sync lo_test_manual dbgroup=lo_test tables=lo_store_manual onetimecopy=1 autokick=0 analyze_after_copy=1
